name: Bug Report
description: Melde einen Fehler mit reproduzierbaren Schritten
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Zusammenfassung
      description: Was ist kaputt?
      placeholder: Kurz und konkret beschreiben
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduktion
      description: Wie kann man den Fehler reproduzieren?
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Tatsächliches Verhalten
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version/Commit
      placeholder: z. B. v5.1.0 oder SHA

  - type: dropdown
    id: area
    attributes:
      label: Bereich
      options:
        - backend
        - frontend
        - gateway
        - docs
        - devops
        - security
