name: Feature Request
description: Schlage eine Verbesserung oder neue Funktion vor
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem/Bedarf
      description: Welches Problem löst das Feature?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Vorschlag
      description: Was soll konkret umgesetzt werden?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Akzeptanzkriterien
      description: Woran erkennen wir, dass es fertig ist?
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priorität
      options:
        - P0
        - P1
        - P2
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Bereich
      options:
        - backend
        - frontend
        - gateway
        - docs
        - devops
        - security
